# Project info
sonar.projectKey=FakhriAiman09_Clinical-Calculator-Competency
sonar.organization=fakhriaiman09
sonar.projectName=Clinical-Calculator-Competency
sonar.sourceEncoding=UTF-8
sonar.python.version=3.13

# Source and test folders
sonar.sources=frontend/src,server/socketio,python
sonar.tests=frontend/__tests__,python/bert/test,python/svm/test,python/infer/test
sonar.test.inclusions=frontend/__tests__/**,python/**/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Exclude copied folders, coverage output, build files, and static assets
sonar.exclusions=mcq-sample-collect/**,testing/**,testing/coverage/**,testing/coverage/lcov-report/**,frontend/coverage/**,frontend/lcov-report/**,**/node_modules/**,**/.next/**,**/public/**,**/*.svg,**/*.png,**/*.ico,**/*.ipynb

# Coverage report
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info

# Ignore tests, copied folders, and generated files in duplication check
sonar.cpd.exclusions=mcq-sample-collect/**,testing/**,testing/coverage/**,testing/coverage/lcov-report/**,frontend/__tests__/**,python/**/test/**,frontend/coverage/**,frontend/lcov-report/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/node_modules/**,**/.next/**,**/public/**,**/*.svg,**/*.png,**/*.ico,**/*.ipynb