name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # pinned v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        # pinned
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
