name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # pinned v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@e44258b109568baa0df60ed515909fc6c72cba92
        # pinned to v2 commit SHA
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
